// INFO
const worst=(S,k)=>{const u=weakest(S,k);return `${u.nome} (${fm(S.st[u.uf].idx[k],0)})`};
const secTip=(S,k,txt)=>{const v=avgIdx(S,k),o=S.nb[k],d=v-o;return `${txt}<br><br><b>Agora:</b> índice nacional ${fm(v,0)} (${sg(d,1)} desde o início). Estado mais frágil: ${worst(S,k)}.`};
const INFO={
pib:{t:'PIB',d:'Soma de tudo que o país produz em um ano. É a base da receita do governo e da renda por habitante.',how:'Cresce com educação, tecnologia, infraestrutura e investimento privado. Estados mais pobres crescem mais rápido quando recebem aportes (efeito de alcance).',tip:S=>`Meta do jogo: elevar o PIB <b>per capita</b>, não só o PIB. Crescimento de 3,5% ao ano dobra a renda em cerca de 20 anos.`},
g:{t:'Crescimento',d:'Variação anualizada do PIB real no trimestre.',how:'Cada setor soma ao crescimento conforme o quanto seu índice subiu acima do ponto de partida. Peso: educação e tecnologia (maior), infraestrutura, saúde, segurança, social e ambiente (menor). Inflação acima de 6% e déficit alto reduzem o crescimento.',tip:S=>gl(S,2)<1.5?'Crescimento fraco: o que mais rende no longo prazo é educação, tecnologia e infraestrutura. Cortar impostos dá fôlego imediato, mas reduz a receita.':'Crescimento saudável. Para sustentá-lo, evite que os índices decaiam: cada setor perde pontos todos os anos se o aporte ficar abaixo da base.'},
infl:{t:'Inflação',d:'Alta anual dos preços. A meta é de 3 a 5%.',how:'Sobe com déficit público alto e com crescimento acima de cerca de 3,5% (superaquecimento). Alguns eventos e leis também a empurram. Acima de 6% reduz o crescimento e derruba a aprovação.',tip:S=>S.infl>5.5?'Inflação alta. Reduza o déficit (menos aportes ou mais receita) ou aprove o arcabouço fiscal. Desacelerar o crescimento também ajuda.':'Inflação sob controle. Cuidado com estímulos fiscais fortes em economia aquecida.'},
unem:{t:'Desemprego',d:'Parcela da força de trabalho sem emprego.',how:'Acompanha o crescimento: cada ponto de crescimento acima de 0 puxa o desemprego para baixo ao longo do tempo. Eventos de recessão ou de requalificação o alteram.',tip:S=>S.unem>8?'Desemprego alto: crescimento sustentado e investimento privado são a saída. Frentes de trabalho só aliviam por pouco tempo.':'Mercado de trabalho aquecido, o que ajuda a aprovação.'},
dr:{t:'Dívida/PIB',d:'Dívida bruta do governo dividida pelo PIB.',how:'Cresce quando a despesa (obrigatória, aportes e juros) supera a receita. Cai com crescimento, inflação moderada e superávit. Acima de 95% as agências ameaçam rebaixar a nota.',tip:S=>drNow(S)>85?'Dívida elevada: juros altos consomem o orçamento. Considere a reforma da previdência, o arcabouço fiscal ou privatizações.':'Há espaço fiscal. Dívida baixa melhora a nota de crédito e reduz os juros.'},
rate:{t:'Juros da dívida',d:'Taxa média paga sobre a dívida pública.',how:'Depende da nota de crédito: cada ponto de nota abaixo de 43 soma 0,07 ponto percentual. Multiplicada pela dívida, vira despesa de juros no orçamento.',tip:S=>`Despesa anual de juros: R$ ${fm(fiscal(S).intr,0)} bi, equivalente a ${fm(fiscal(S).intr/fiscal(S).gd*100,1)}% do PIB. Melhorar a nota de crédito reduz esse custo ano após ano.`},
rt:{t:'Nota de crédito',d:'Índice de 0 a 100 da confiança dos credores no país. Faixas: CCC, B, BB, BBB, A.',how:'Melhora com dívida baixa, déficit pequeno, inflação controlada, crescimento e reformas (arcabouço fiscal, previdência, tributária). Piora com o contrário.',tip:S=>`Nota atual: ${ratingLetter(S.rt)} (${fm(S.rt,0)}). Cada faixa melhor derruba os juros e libera orçamento para investir.`},
I:{t:'Investimento privado',d:'Parcela do PIB que as empresas investem em máquinas, fábricas e obras.',how:'Tende a um alvo que sobe com infraestrutura, segurança, educação, nota de crédito e reformas, e cai com inflação e dívida altas. Cada ponto acima de 15% do PIB soma cerca de 0,12 ponto percentual de crescimento ao ano.',tip:S=>S.I<14?'Investimento privado fraco. Segurança e infraestrutura atraem capital; reformas tributária, de concessões e inovação ajudam.':'Capital privado reforçando o crescimento. Mantenha previsibilidade fiscal.'},
pc:{t:'PIB per capita',d:'PIB dividido pela população. Mede a riqueza média por habitante.',how:'É o principal componente da nota final (40%). Crescimento sustentado ao longo de 28 anos pesa mais que picos curtos.',tip:S=>{const L=legacy(S);return `Variação desde 2027: ${sg(L.pcg,0)}%. Para a nota máxima nessa dimensão: cerca de 4% ao ano.`}},
appr:{t:'Aprovação',d:'Parcela da população que aprova o seu governo, ponderada pela população dos estados.',how:'Depende da afinidade ideológica com o eleitorado, serviços públicos, crescimento, inflação, desemprego e impostos. É uma restrição: sem aprovação você perde a eleição e o jogo termina antes.',tip:S=>`Rejeição nacional: ${fm(natRej(S),0)}%. Você só precisa de aprovação suficiente para vencer as eleições (${ELECT.join(', ')}). Entre elas, priorize a economia.`}};
const SINFO={
edu:{t:'Educação',d:'Qualidade da educação básica e técnica.',how:'Maior peso no crescimento de longo prazo (capital humano). Retorno lento: demora anos para aparecer, mas dura. Também atrai investimento privado.',tip:S=>secTip(S,'edu','Mantenha sempre o aporte acima de 100% da base em estados atrasados: o retorno é maior onde o índice é baixo.')},
saude:{t:'Saúde',d:'Acesso e qualidade do SUS.',how:'Peso médio no crescimento (trabalhadores saudáveis) e grande efeito na aprovação. Tem o maior peso no orçamento (28%).',tip:S=>secTip(S,'saude','Bom para aprovação. Se precisar economizar, evite cortar aqui antes de eleições.')},
infra:{t:'Infraestrutura',d:'Estradas, ferrovias, portos, energia e saneamento.',how:'Eleva a produtividade e atrai investimento privado. Efeito mais rápido que o da educação. Estados muito atrasados em infraestrutura sofrem eventos de colapso logístico.',tip:S=>secTip(S,'infra','Em geral é o setor com melhor retorno de médio prazo. Concessões privadas somam ao seu aporte.')},
seg:{t:'Segurança',d:'Policiamento, inteligência e sistema prisional.',how:'Ajuda o crescimento e é pré-condição para investimento privado. Alta aprovação no Sul, Centro-Oeste e Sudeste. Índice abaixo de 40 dispara alarme.',tip:S=>secTip(S,'seg','Afeta a confiança das empresas. Governos de direita rendem mais aqui.')},
tech:{t:'Ciência e tecnologia',d:'Pesquisa, universidades e inovação.',how:'Peso alto no crescimento por real investido, mas orçamento pequeno (5% da base). Retorno lento e concentrado em estados desenvolvidos.',tip:S=>secTip(S,'tech','É barato: aportes de 130 a 150% custam pouco e movem o crescimento. Exige educação forte para render.')},
social:{t:'Assistência social',d:'Transferências de renda e proteção social.',how:'Efeito pequeno no crescimento, forte na aprovação (principalmente no Nordeste e Norte) e na redução da desigualdade, que conta na nota final.',tip:S=>secTip(S,'social','Governos de esquerda rendem mais aqui. Equilibre com o orçamento.')},
amb:{t:'Meio ambiente',d:'Fiscalização, florestas e licenciamento.',how:'Efeito pequeno no crescimento. Pesa pouco na aprovação geral e mais em eleitorados de esquerda.',tip:S=>secTip(S,'amb','Orçamento pequeno (4%). Útil para eventos climáticos e reputação.')}};
